argocd: 
  namespace: argocd
  project: 'opensource'
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: core-data-platform
  sourceRepoURL: 'https://github.com/tushar07232769/ecsp-helm-charts-main'
  targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - RespectIgnoreDifferences=true  


applications:
  hivemq:
    enabled: false
  kafka:
    enabled: false
  mongodb-sharded:
    enabled: true
  namespace-config:
    enabled: false
  nginx:
    enabled: true
  postgresql:
    enabled: true
  redis:
    enabled: true
  zk:
    enabled: false                
