argocd: 
  namespace: argocd
  project: 'opensource'
  destination: 
    server: 'https://kubernetes.default.svc'
    namespace: ecsp-services
  sourceRepoURL: 'https://github.com/tushar07232769/ecsp-helm-charts-main'
  targetRevision: 'main'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - RespectIgnoreDifferences=true

applications:
  association:
    enabled: true
  device-auth:
    enabled: true
  device-message:
    enabled: true  
